/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import GameInfo.Music;
import GameInfo.Player;
import GameInfo.Room;
import JudgeStatus.JudgeStatus;
import SendingData.SSLClient;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.IOException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.json.JSONException;
import org.json.JSONObject;

/**
 *
 * @author Wei
 */
public class Login extends javax.swing.JFrame {

    private String password = "";
    private String username;
    private static final int tempuserid = 0;
    
    private int status;
    private double balance;
    private String nickname;
    private int rank;
    private int credit;
    private int userid;
    private double factor1;
    private double factor2;
    private double factor3;

    public static String STATUS = "status";
    public static String RES = "result";
    public static String KEY_BALANCE = "balance";
    public static String KEY_NICKNAME = "nickname";
    public static String KEY_RANK = "rank";
    public static String KEY_CREDIT = "credit";
    public static String KEY_USERID = "userid";
    public static String KEY_FACTOR1 = "factor1";
    public static String KEY_FACTOR2 = "factor2";
    public static String KEY_FACTOR3 = "factor3";
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        Room.initial();
        //System.out.println(user_name.getText());
        //System.out.println(user_pass.getPassword());
        user_name.addMouseListener(new MouseAdapter(){

            @Override
            public void mouseClicked(MouseEvent e) {
                if(user_name.getText().equals("User Name")){
                    user_name.setText("");
                }
            }
        });
        
        user_pass.addMouseListener(new MouseAdapter(){

            @Override
            public void mouseClicked(MouseEvent e) {
                //if(user_pass.getPassword().equals("Password")){
                    user_pass.setText("");
                //}
            }
        });
        
        Music.initial(1);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        register = new javax.swing.JButton();
        log_in = new javax.swing.JButton();
        user_pass = new javax.swing.JPasswordField();
        user_name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        register.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        register.setText("Signup");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        jPanel1.add(register);
        register.setBounds(410, 330, 80, 21);

        log_in.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        log_in.setText("Login");
        log_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_inActionPerformed(evt);
            }
        });
        jPanel1.add(log_in);
        log_in.setBounds(330, 330, 70, 21);

        user_pass.setText("Password");
        user_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_passActionPerformed(evt);
            }
        });
        jPanel1.add(user_pass);
        user_pass.setBounds(350, 300, 140, 20);

        user_name.setText("User Name");
        user_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_nameActionPerformed(evt);
            }
        });
        jPanel1.add(user_name);
        user_name.setBounds(350, 270, 140, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/img/imgo.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 530);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void user_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_passActionPerformed
        // TODO add your handling code here:

        //JOptionPane.showMessageDialog(null, "Wrong Password!");
    }//GEN-LAST:event_user_passActionPerformed

    private void user_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_nameActionPerformed

    private void log_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_inActionPerformed
        // TODO add your handling code here:
        password = "";
        char[] temp;
        temp = user_pass.getPassword();
        //password = user_pass.getPassword()+"";
        for (int i = 0; i < user_pass.getPassword().length; i++) {
            password = password + temp[i];
            //System.out.print(temp[i]);
        }
        //System.out.println("password: " + password);
        //System.out.println();
        try {
            MessageDigest md = MessageDigest.getInstance("MD5");
            md.update(password.getBytes());
            byte[] digest = md.digest();
            StringBuffer sb = new StringBuffer();
            for (byte b : digest) {
                sb.append(String.format("%02x", b & 0xff));
            }
            password = sb.toString();
            //System.out.println("password: " + sb.toString());
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }

        username = user_name.getText();
        //System.out.println("username: " + username);
        JSONObject response = null;
        try {
            response = SSLClient.postMessage(getMessge());
        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        
        JSONObject result = null;
        
        try {
            status = response.getInt(STATUS);
            //System.out.println(status);
            //static method
            if(JudgeStatus.OutputStatus(status) == false){
                return;
            }
            result = response.getJSONObject(RES);
        } catch (JSONException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            nickname = result.getString(KEY_NICKNAME);
            balance = result.getDouble(KEY_BALANCE);
            rank = result.getInt(KEY_RANK);
            credit = result.getInt(KEY_CREDIT);
            userid = result.getInt(KEY_USERID);
            factor1 = result.getDouble(KEY_FACTOR1);
            factor2 = result.getDouble(KEY_FACTOR2);
            factor3 = result.getDouble(KEY_FACTOR3);
        } catch (JSONException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        //System.out.println("CREDIT" + credit);
        Player.initial(balance,nickname,rank,credit,userid,factor1,factor2,factor3);
        
        //System.out.println(response);
        HomePage h = null;
        try {
            h = new HomePage();
        } catch (JSONException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        h.setSize(800,450);
        h.setLocation(0,0);
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_log_inActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
        Registration f = new Registration();
        f.setSize(300, 400);
        f.setLocation(300, 200);
        f.setVisible(true);
    }//GEN-LAST:event_registerActionPerformed

    public JSONObject getMessge() {
        JSONObject test = new JSONObject();
        try {
            test.put("opt", "login");
            test.put("userid", tempuserid);
            JSONObject info = new JSONObject();
            info.put("username", username);
            info.put("passwd", password);
            test.put("info", info);
        } catch (JSONException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        //System.out.println(test);
        return test;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton log_in;
    private javax.swing.JButton register;
    private javax.swing.JTextField user_name;
    private javax.swing.JPasswordField user_pass;
    // End of variables declaration//GEN-END:variables
}
