/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import GameInfo.Player;
import JudgeStatus.JudgeStatus;
import SendingData.SSLClient;
import static UI.CreateRoom.STATUS;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.json.JSONException;
import org.json.JSONObject;

/**
 *
 * @author Wei
 */
public class Purchase extends javax.swing.JFrame {

    private double Money;
    private String Brand;
    private String CardNum;
    private String Date;
    private String CardHolder;
    private int CVV;
    private int ZipCode;
    private int userid;
    private int status;
   
    /**
     * Creates new form Purchase
     */
    public Purchase() {
        initComponents();
        jPaymentInfo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPaymentInfo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jBrand = new javax.swing.JComboBox();
        jCardNumber = new javax.swing.JTextField();
        jMonth = new javax.swing.JComboBox();
        jYear = new javax.swing.JComboBox();
        jCardHolder = new javax.swing.JTextField();
        jCVV = new javax.swing.JTextField();
        jZipCode = new javax.swing.JTextField();
        jBack = new javax.swing.JButton();
        jPayNow = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPoints = new javax.swing.JPanel();
        j10 = new javax.swing.JButton();
        j20 = new javax.swing.JButton();
        j50 = new javax.swing.JButton();
        j100 = new javax.swing.JButton();
        j200 = new javax.swing.JButton();
        j500 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFocusable(false);
        setResizable(false);

        jPanel1.setLayout(null);

        jPaymentInfo.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PAYMENT INFORMATION");
        jPaymentInfo.add(jLabel2);
        jLabel2.setBounds(10, 10, 166, 17);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Brand");
        jPaymentInfo.add(jLabel3);
        jLabel3.setBounds(10, 66, 33, 17);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Card Number");
        jPaymentInfo.add(jLabel4);
        jLabel4.setBounds(10, 107, 77, 17);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Expiry Dtae");
        jPaymentInfo.add(jLabel5);
        jLabel5.setBounds(10, 148, 67, 17);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Card Holder");
        jPaymentInfo.add(jLabel6);
        jLabel6.setBounds(10, 189, 68, 17);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CVV");
        jPaymentInfo.add(jLabel7);
        jLabel7.setBounds(10, 230, 27, 17);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Zip Code");
        jPaymentInfo.add(jLabel8);
        jLabel8.setBounds(10, 271, 51, 17);

        jBrand.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jBrand.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Visa", "MasterCard", "American Express", "Discover" }));
        jPaymentInfo.add(jBrand);
        jBrand.setBounds(172, 63, 117, 23);

        jCardNumber.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPaymentInfo.add(jCardNumber);
        jCardNumber.setBounds(172, 104, 163, 23);

        jMonth.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jPaymentInfo.add(jMonth);
        jMonth.setBounds(172, 145, 42, 23);

        jYear.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));
        jPaymentInfo.add(jYear);
        jYear.setBounds(232, 145, 72, 23);

        jCardHolder.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPaymentInfo.add(jCardHolder);
        jCardHolder.setBounds(172, 186, 163, 23);

        jCVV.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPaymentInfo.add(jCVV);
        jCVV.setBounds(172, 227, 141, 23);

        jZipCode.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPaymentInfo.add(jZipCode);
        jZipCode.setBounds(172, 268, 163, 23);

        jBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/img/btn_back.jpg"))); // NOI18N
        jBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackActionPerformed(evt);
            }
        });
        jPaymentInfo.add(jBack);
        jBack.setBounds(339, 315, 80, 25);

        jPayNow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/img/btn_paynow.jpg"))); // NOI18N
        jPayNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPayNowActionPerformed(evt);
            }
        });
        jPaymentInfo.add(jPayNow);
        jPayNow.setBounds(431, 315, 94, 25);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/img/HomePage_bg.jpg"))); // NOI18N
        jPaymentInfo.add(jLabel11);
        jLabel11.setBounds(0, 0, 570, 360);

        jPanel1.add(jPaymentInfo);
        jPaymentInfo.setBounds(0, 0, 570, 360);

        jPoints.setLayout(null);

        j10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j10ActionPerformed(evt);
            }
        });
        jPoints.add(j10);
        j10.setBounds(60, 70, 114, 102);

        j20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j20ActionPerformed(evt);
            }
        });
        jPoints.add(j20);
        j20.setBounds(210, 70, 114, 102);

        j50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j50ActionPerformed(evt);
            }
        });
        jPoints.add(j50);
        j50.setBounds(360, 70, 114, 102);

        j100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j100ActionPerformed(evt);
            }
        });
        jPoints.add(j100);
        j100.setBounds(60, 200, 114, 102);

        j200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j200ActionPerformed(evt);
            }
        });
        jPoints.add(j200);
        j200.setBounds(210, 200, 114, 102);

        j500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j500ActionPerformed(evt);
            }
        });
        jPoints.add(j500);
        j500.setBounds(360, 200, 114, 102);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Select Money Amount");
        jPoints.add(jLabel9);
        jLabel9.setBounds(30, 30, 215, 22);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/img/btn_back.jpg"))); // NOI18N
        jPoints.add(jButton1);
        jButton1.setBounds(480, 320, 80, 28);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/img/HomePage_bg.jpg"))); // NOI18N
        jPoints.add(jLabel10);
        jLabel10.setBounds(0, 0, 570, 360);

        jPanel1.add(jPoints);
        jPoints.setBounds(0, 0, 570, 360);

        jLabel1.setFocusable(false);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 570, 360);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void j20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j20ActionPerformed
        // TODO add your handling code here:
        Money = 20;
        jPoints.setVisible(false);
        jPaymentInfo.setVisible(true);
    }//GEN-LAST:event_j20ActionPerformed

    private void j200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j200ActionPerformed
        // TODO add your handling code here:
        Money = 200;
        jPoints.setVisible(false);
        jPaymentInfo.setVisible(true);
    }//GEN-LAST:event_j200ActionPerformed

    private void j10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j10ActionPerformed
        // TODO add your handling code here:
        Money = 10;
        jPoints.setVisible(false);
        jPaymentInfo.setVisible(true);
    }//GEN-LAST:event_j10ActionPerformed

    private void j50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j50ActionPerformed
        // TODO add your handling code here:
        Money = 50;
        jPoints.setVisible(false);
        jPaymentInfo.setVisible(true);
    }//GEN-LAST:event_j50ActionPerformed

    private void j100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j100ActionPerformed
        // TODO add your handling code here:
        Money = 100;
        jPoints.setVisible(false);
        jPaymentInfo.setVisible(true);
    }//GEN-LAST:event_j100ActionPerformed

    private void j500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j500ActionPerformed
        // TODO add your handling code here:
        Money = 500;
        jPoints.setVisible(false);
        jPaymentInfo.setVisible(true);
    }//GEN-LAST:event_j500ActionPerformed

    private void jBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackActionPerformed
        // TODO add your handling code here:
        jPoints.setVisible(false);
        jPaymentInfo.setVisible(true);
    }//GEN-LAST:event_jBackActionPerformed

    private void jPayNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPayNowActionPerformed
        // TODO add your handling code here:
        Brand = jBrand.getSelectedItem().toString();
        CardNum = jCardNumber.getText();
        Date = jMonth.getSelectedItem() + "" + jYear.getSelectedItem() + "";
        CardHolder = jCardHolder.getText();
        CVV = Integer.parseInt(jCVV.getText());
        ZipCode = Integer.parseInt(jZipCode.getText());
        Player.GetPlayer().SetBalance(Money + Player.GetPlayer().GetBalance());
        
        JSONObject response = null;
        try {
            response = SSLClient.postMessage(getMessge());
        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        
        try {
            status = response.getInt(STATUS);
        } 
        catch (JSONException ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (JudgeStatus.OutputStatus(status) == false) {
            return;
        }
        this.dispose();
    }//GEN-LAST:event_jPayNowActionPerformed

    public JSONObject getMessge() {
        JSONObject test = new JSONObject();
        try {
            
            test.put("opt", "purchase");
            userid = Player.GetPlayer().GetUserId();
            test.put("userid", userid);
            JSONObject info = new JSONObject();
            info.put("amount", Money);
            info.put("expire", Date);
            info.put("brand", Brand);
            info.put("cardnumber", CardNum);
            info.put("cardholder", CardHolder);
            info.put("securitynumber", CVV);
            info.put("zipcode", ZipCode);
            test.put("info", info);
        } catch (JSONException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        System.out.println(test);
        return test;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Purchase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton j10;
    private javax.swing.JButton j100;
    private javax.swing.JButton j20;
    private javax.swing.JButton j200;
    private javax.swing.JButton j50;
    private javax.swing.JButton j500;
    private javax.swing.JButton jBack;
    private javax.swing.JComboBox jBrand;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jCVV;
    private javax.swing.JTextField jCardHolder;
    private javax.swing.JTextField jCardNumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox jMonth;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jPayNow;
    private javax.swing.JPanel jPaymentInfo;
    private javax.swing.JPanel jPoints;
    private javax.swing.JComboBox jYear;
    private javax.swing.JTextField jZipCode;
    // End of variables declaration//GEN-END:variables
}
